---
all:
  children:
    devices:
      children:
        ios_router:
          hosts:
            csr1:
            csr2:
        iosxr_router:
          hosts:
            xrv1:
        asa_firewall:
          hosts:
            asav1:
        nxos_leaf:
          hosts:
            n3k1:
        aireos_wlc:
          hosts:
            vwlc1:
...
