---

- name: First Network Playbook
  connection: network_cli
  gather_facts: false
  hosts: 'csr1'
  tasks:

    - name: configure hostname
      ios_config:
        lines:
          - hostname csr1k-new_hostname
   
    - name: Gather IOS Facts
      ios_facts: 
      when: ansible_network_os == 'ios'

    - name: Display facts
      debug: 
        msg: "The hostname is {{ ansible_net_hostname  }} and the os is {{ ansible_net_version }}"
